// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA62uWLRpGTSsGZefox2w0kdnGBIMzJrrg',
    appId: '1:25137608488:web:d362aea0c2363c1956021d',
    messagingSenderId: '25137608488',
    projectId: 'alarmouse-6e8df',
    authDomain: 'alarmouse-6e8df.firebaseapp.com',
    storageBucket: 'alarmouse-6e8df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrZG0aC53zzIyZxYQDeEqmLLna4T7Q43c',
    appId: '1:25137608488:android:032715777caf783c56021d',
    messagingSenderId: '25137608488',
    projectId: 'alarmouse-6e8df',
    storageBucket: 'alarmouse-6e8df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ZeOSEMQGJtK2_43fCdDAoMR4AqqL8DU',
    appId: '1:25137608488:ios:11d2647c41046e8556021d',
    messagingSenderId: '25137608488',
    projectId: 'alarmouse-6e8df',
    storageBucket: 'alarmouse-6e8df.appspot.com',
    androidClientId: '25137608488-b6lob0kqe6l99i4rch7kcv84nccjc58v.apps.googleusercontent.com',
    iosClientId: '25137608488-cl31sosor4msaubqucm3jhjnk2t1ugv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9ZeOSEMQGJtK2_43fCdDAoMR4AqqL8DU',
    appId: '1:25137608488:ios:11d2647c41046e8556021d',
    messagingSenderId: '25137608488',
    projectId: 'alarmouse-6e8df',
    storageBucket: 'alarmouse-6e8df.appspot.com',
    androidClientId: '25137608488-b6lob0kqe6l99i4rch7kcv84nccjc58v.apps.googleusercontent.com',
    iosClientId: '25137608488-cl31sosor4msaubqucm3jhjnk2t1ugv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );
}
